### ISSUE TITLE
preprocessors.shift(...) is not a function

### ISSUE THREAD

**Issue by kentcdodds** [karma-runner/karma#1521]
I think [this commit](https://github.com/karma-runner/karma/commit/8a9c8c739d612f3d5d07cc80231ff85f1395d122) is giving me this error:

> 27 07 2015 15:21:53.351:ERROR [karma]: [TypeError: preprocessors.shift(...) is not a function]
> TypeError: preprocessors.shift(...) is not a function
>     at nextPreprocessor (/Users/kentcdodds/Developer/alianza/admin-portal/node_modules/karma/lib/preprocessor.js:73:28)
>     at /Users/kentcdodds/Developer/alianza/admin-portal/node_modules/karma/lib/preprocessor.js:96:7
>     at /Users/kentcdodds/Developer/alianza/admin-portal/node_modules/karma/node_modules/graceful-fs/graceful-fs.js:76:16
>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

Anything off the top of your head? Everything's working fine with version `0.13.1` but breaks with version `0.13.2`. Do you know what might be the problem? Or do you need me to dig more?

**Comment by Dignifiedquire** [comment]
Thanks for reporting, you are probably right with the commit, but I have no idea how this could happen, as even `[].shift()` should not throw this error. So if you could find some details, on how this occurs I would be very grateful.

**Comment by kentcdodds** [comment]
This is the code that I'm looking at that's blowing up:

```javascript
preprocessors.shift()(content, file, nextPreprocessor)
```

I believe that what's being shifted isn't a function. That's what the error means... Digging...

**Comment by kentcdodds** [comment]
It looks like the line:

```javascript
instances[name] = injector.get('preprocessor:' + name)
```

is actually assigning `instances[name]` to `undefined` which ultimately gets pushed into the `preprocessors` (as undefined) and then this error gets thrown.

The preprocessor I'm working with is [`webpack`](https://github.com/webpack/karma-webpack) (I'm using version `1.6.0`).

**Comment by Dignifiedquire** [comment]
Right, I see, thanks a lot for digging. So the best thing is probably to a) not do the assignment when it fails and b) ensure when pushing into preprocessors that the element is not `undefined`.

**Comment by kentcdodds** [comment]
I agree. In addition, I don't think that this fix will resolve my ultimate issue. Do you know why the webpack preprocessor isn't getting added? Will things work when webpack hasn't yet been added?

**Comment by Dignifiedquire** [comment]
karma-webpack won't work unless you use my fork https://github.com/webpack/karma-webpack/pull/63 that is probably what you are running into

**Comment by kentcdodds** [comment]
Ah, I see. Sounds good. I'll subscribe to that PR so I know when it's merged. Thanks for your work on `karma`! It's beyond invaluable. And thanks for the quick response.

**Comment by LPGhatguy** [comment]
I just hit this issue today with Karma 0.13.10, upgrading from an older version and tyring to get `karma-sourcemap-loader` to work. Has there been any progress on fixing this?

**Comment by yaring** [comment]
Same error here with `0.13.11` :/

**Comment by gejgalis** [comment]
The same error with `0.13.11` on Linux. It works for me on Windows :(
I'm using preprocessor `webpack`

**Comment by TjRus** [comment]
`npm install karma@canary` fixed the problem for me

**Comment by gep13** [comment]
Also seeing this issue.  Any suggestions on how to fix/work around?

**Comment by albohlabs** [comment]
@gep13 I've also run in this error when i was using `karma-sourcemap-loader` cause i forgot to add it to the `plugins` property. 

```js
plugins: [
  …
  'karma-sourcemap-loader'
],
```

So recheck your `karma.conf.js`.

**Comment by cades** [comment]
+1 for karma-live-preprocessor

**Comment by kostia** [comment]
Same issue with 0.13.16. :crying_cat_face:

**Comment by Dignifiedquire** [comment]
Please everyone can you test if https://github.com/karma-runner/karma/pull/1777 works for you? I'm not able to reproduce the issue myself, so I can only guess atm.
