### ISSUE TITLE
Cannot find module 'flatted/cjs'

### ISSUE THREAD

**Issue by Aladdin-ADD** [karma-runner/karma#3222]
seems it should be in deps,  than in dev deps.

it was introduced in https://github.com/karma-runner/karma/commit/fb05fb134fb67f8879711054b6e0da0febbbdc7b

**Comment by limonte** [comment]
same here: https://github.com/sweetalert2/sweetalert2/issues/1315

**Comment by Aladdin-ADD** [comment]
fixed by #3222, and released in v3.1.3.

**Comment by bergie** [comment]
Seems to have been fixed with Karma 3.1.3: https://github.com/noflo/noflo-browser/pull/122
