### ISSUE TITLE
v0.13.22 is a breaking change from v0.13.21

### ISSUE THREAD

**Issue by redfox05** [karma-runner/karma#1995]
After upgrading from v0.13.21 to v0.13.22 via npm update (our package.json has "karma": "^0.13.21") the tests suddenly fail on all our Build environments. This I would class as a breaking change, as a change in the 'hotfix' version (The last part of a version number) should not result in anything breaking in the application it is used. Equally worrying is that there is nothing mentioned in the changelog.md for v0.13.21 to quickly check what has changed.

### Expected behavior
The test passed as the "expect" part of the test is commented out. This works fine in v0.13.21
`PhantomJS 2.1.1 (Mac OS X 0.0.0): Executed 2 of 2 SUCCESS (0.004 secs / 0.035 secs)`

### Actual behavior
The test fails in v0.13.22 with the following error:
```
[1A[2KPhantomJS 2.1.1 (Linux 0.0.0) Controller: XXXXXXXX should attach a list of items to the scope FAILED
	TypeError: undefined is not a function (evaluating 'angular.element.cleanData(cleanUpNodes)') in 
```
### Enviroment Details
- Karma tests from via grunt using karma and PhantomJS 2.1.1
- Karma version: Karma v0.13.22 upgraded from Karma v0.13.21
- Relevant part of your `karma.config.js` file: Let me know if you need any of this, as its project specific content, which you may not need.
- package.json: `"karma": "^0.13.21",`

### Steps to reproduce the behaviour
Code in the relevant test.js file:
```
  it('should attach a list of items to the scope', function () {
    //expect(Items.productItems).toEqual(['Towel', 'Coat']);
  });
```

**Comment by dignifiedquire** [comment]
I'm very sure this is not Karmas fault. 0.13.22 and 0.13.21 are identical in code, except for a temp file that I accidentally shipped in the npm release. So it's much more likely that some dependency change is responsible for this change which is not directly related to Karma. You can see the code difference here: https://github.com/karma-runner/karma/compare/v0.13.21...v0.13.22

**Comment by briangershon** [comment]
Short answer:

This solved the problem for me about 15 minutes ago: https://github.com/facebook/react-native/issues/6595

They must have put left-pad@0.0.3 back.

Long answer:

Today I ran into this error:

```
npm ERR! No compatible version found: left-pad@0.0.3
npm ERR! Valid install targets:
npm ERR! 0.0.9
```

At one point changing this from `0.13.22` to `0.13.21` fixed the issue, but after a couple of hours of trying to narrow down (was also eye'ing `grunt-karma` as a possible problem), my original `package.json` magically worked with `0.13.22`, so maybe a broken dependency somewhere fixed itself.

At the end of the day, latest karma 0.13.22 and latest grunt-karma 0.12.2 worked fine.

**Comment by dignifiedquire** [comment]
thanks @briangershon for the info closing this for now

**Comment by Afshintm** [comment]
I am still getting this issue 
here is my installed packages:
 
grunt-karma@0.12.2
karma@0.13.22
karma-jasmine@0.1.6

Can you please help ?
