### PR TITLE
fix: add missing dep flatted (fixes #3222)

### LINKED ISSUE #3222: Cannot find module 'flatted/cjs'
seems it should be in deps,  than in dev deps.

it was introduced in https://github.com/karma-runner/karma/commit/fb05fb134fb67f8879711054b6e0da0febbbdc7b

### PR DESCRIPTION
**Pull request by Aladdin-ADD**
the tests failed on node 6, but cannot be related to this change.

### CODE REVIEW

**Comment by Aladdin-ADD** [comment]
I signed it!
