### ISSUE TITLE
TypeError: '[object Object]' is not a function (evaluating 'obj.toJSON()') after upgrade from 0.12.16 to 0.13.*

### ISSUE THREAD

**Issue by rhoggSugarcrm** [karma-runner/karma#1686]
I'm using Karma with gulp (directly, not through gulp-karma) and attempted to upgrade Karma to version 0.13 and now running the test suite fails with a TypeError. I tried 0.13.15, 0.13.1, and 0.13.10 and they all have the same problem.
```
$ gulp karma
[11:57:58] Using gulpfile ~/<path>/gulpfile.js
[11:57:58] Starting 'karma'...
WARN `start` method is deprecated since 0.13. It will be removed in 0.14. Please use
  server = new Server(config, [done])
  server.start()
instead.
03 11 2015 11:57:59.172:INFO [karma]: Karma v0.13.15 server started at http://localhost:9876/
03 11 2015 11:57:59.177:INFO [launcher]: Starting browser PhantomJS
03 11 2015 11:58:00.445:INFO [PhantomJS 1.9.8 (Mac OS X 0.0.0)]: Connected on socket NNFnU6fvJSQUedQkAAAA with id 83297669
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  TypeError: '[object Object]' is not a function (evaluating 'obj.toJSON()')
  at http://localhost:9876/socket.io/socket.io.js:5362
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.161 secs / 0 secs)
[11:58:00] Finished 'karma' after 1.73 s
```
For the record, the problem is not solved by fixing the usage of the deprecated interface.

This is possibly related to #1684. Note also that this is not specific to PhantomJS - the Firefox and Chrome launchers have the same problem.

```bash
$ node --version; npm --version
v4.2.1
2.14.7
```

Thank you for your assistance!

**Comment by rhoggSugarcrm** [comment]
After doing some investigation, this issue is caused by https://github.com/Automattic/has-binary/issues/4.

I don't think there's anything that needs to be done at your end.

Leaving open for now, but your call.

**Comment by rhoggSugarcrm** [comment]
Resolved now that Socket.io has made a release that includes the fix for has-binary.

**Comment by Dignifiedquire** [comment]
Thanks @rhoggSugarcrm for keeping track of this :)
