### PR TITLE
use lodash find() instead of Array.prototype.find

### PR DESCRIPTION
**Pull request by kketch**
When i upgraded to from Karma 0.12.x to 0.13.3, my karma setup stopped working.

file-list.js uses ES6 Array.prototype.find which of course fails with `TypeError: undefined is not a function` in normal node installations (without the harmony flag).

Replacing Array.prototype.find() with lodash.find() (which is already used in other places in file-list.js) seems to fix the issue.

### CODE REVIEW

**Comment by Dignifiedquire** [comment]
Thanks, could you change the commit message to follow our [convention](http://karma-runner.github.io/0.13/dev/git-commit-msg.html) please?

**Comment by kketch** [comment]
fixed the commit message

**Comment by Dignifiedquire** [comment]
Thanks :octocat:

**Comment by Dignifiedquire** [comment]
Released in https://github.com/karma-runner/karma/releases/tag/v0.13.5
